name: "ci"
on:
  pull_request:

permissions:
  contents: read

jobs:
  pr:
    name: "pr"
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
